/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-application-conventions")
}

repositories {
    flatDir {
        dirs("libs")
    }
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(files("libs/mylib.jar", "libs/commons-collections4-4.4.jar"))
    // https://mvnrepository.com/artifact/org.apache.commons/commons-lang3
    implementation("org.apache.commons:commons-lang3:3.0")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.App"
}
