/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;
import static main.java.org.variouslib.mylib.MyLib.itsAlive;

import org.apache.commons.text.WordUtils;
import org.apache.commons.lang3.*;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));

        //reverse result
        System.out.println("=================");
        System.out.println(StringUtils.reverse(result));

        //static method from third-party library 'mylib'
        System.out.println("=================");
        itsAlive();
    }
}
